### ISSUE TITLE
Sound not working properly (x86)

### ISSUE THREAD

**Issue by Manurocker95** [snesrev/zelda3#10]
The game suffers tons of sound stuttering on x86 version (running on x64 bits). This does not happen with the x64 version.

**Comment by yne** [comment]
As stated by [LakeSnes](https://github.com/elzo-d/LakeSnes) README, it optimisation is ...

> ... is still quite bad though, especially when compared to emulators like BSNES or SNES9X (it uses around 80% of one core, whereas SNES9X only uses around 15%).

Juste to be sure it's not a code issue, I've tested:
- x86 on x64 using GCC -O2
- x64 on x64 using GCC -O2
Without stuttering.

My guess is that your x64 CPU is struggling to handle the DSP emulation in x86 mode.

You can confirm by using your task manager and see if one core is at 100%

**Comment by snesrev** [comment]
Labelling this as wontfix for now, sounds like some cpu issue or whatever
