### ISSUE TITLE
Jumpy grass rabbit doesn't give you its heart

### ISSUE THREAD

**Issue by Goodlyay** [snesrev/zelda3#101]
The creature in the swamp below Link's house doesn't explode into a heart after saying "take it, thief!". Seems to be reproducible every time I hit 3, go to swamp, and cut grass under rabbit while it's in mid-air.

In case it's relevant, these are the settings I had when I got the result.
![image](https://user-images.githubusercontent.com/7892772/191147085-cf21c32b-9859-4f87-b05d-357aee0970f8.png)

**Comment by FitzRoyX** [comment]
Good catch. To elaborate, his name is Toppo and his death drops are just hearts and rupees, but his drops are much better if you do this.

**Comment by Goodlyay** [comment]
> Good catch. To elaborate, his name is Toppo and his death drops are just hearts and rupees, but his drops are much better if you do this.

I never knew it had a name. Is it mentioned in-game somewhere?
