### ISSUE TITLE
Remaining issues with 240 vres extension

### ISSUE THREAD

**Issue by FitzRoyX** [snesrev/zelda3#102]
1. In 4:3 (16:15), overscan area is not unmasked ingame. Also, the mode7 map has a string of black tiles down the middle.
2. In all aspects, the title screen and character selection screens are not unmasked. The triforce animation visibly starts behind the mask.

**Comment by snesrev** [comment]
is 1. fixed in master?

**Comment by FitzRoyX** [comment]
Yes. The only thing left that I can tell is character select.
