### ISSUE TITLE
Compilation failure.

### ISSUE THREAD

**Issue by DaBanana64** [snesrev/zelda3#103]
The latest commit fails to compile and it seems like its related to the new secondary item slot feature. 
![image](https://user-images.githubusercontent.com/82652849/191591262-a7806b17-5e01-4a99-a3b8-bb86b1d5cb40.png)

**Comment by snesrev** [comment]
I can't try on linux. Does it work now?

**Comment by patrickmollohan** [comment]
Linux works!

**Comment by DaBanana64** [comment]
> I can't try on linux. Does it work now?

![image](https://user-images.githubusercontent.com/82652849/191615311-bf877abd-da48-4bd8-a312-ed5b00e83c4f.png)
👍🏼
