### ISSUE TITLE
Text bug when enabling orange/yellow color for max rupees/bombs/arrows

### ISSUE THREAD

**Issue by JasonShearer** [snesrev/zelda3#110]
![zelda3_2022-09-22_05-51-46](https://user-images.githubusercontent.com/14334181/191751908-3e525fe2-2050-4b42-b241-432c77a63d03.png)

![zelda3_2022-09-22_05-51-50](https://user-images.githubusercontent.com/14334181/191751910-8a858ef5-2abd-47de-92a4-a0e31d024bf5.png)

![zelda3_2022-09-22_05-51-44](https://user-images.githubusercontent.com/14334181/191751912-988152d6-dbd8-43fc-a1dc-0f39c9f6e302.png)

**Comment by snesrev** [comment]
I had made a mistake with git and for some reason there was a merge commit in the history with two different versions of the colored text feature. I force pushed it away, you might have to use 'git reset --hard master'

**Comment by snesrev** [comment]
Ok something is wrong with my git skills. Now the broken thing ended up in that PR by someone else. Try fetch again please..

**Comment by JasonShearer** [comment]
It's fixed now. Thank you.
