### ISSUE TITLE
Graphics Glitch in Dark World treasure chest game after choosing item

### ISSUE THREAD

**Issue by aleczabaleta** [snesrev/zelda3#113]
![zelda3 chest game glitch](https://user-images.githubusercontent.com/101672814/191837646-3006c35d-6efc-43f0-a979-67f239322e4f.png)

When link opens a chest in the Treasure Chest Game house, an "open chest" sprite appears underneath Link and the chosen chest appears locked. The glitch is purely visual, as Link gets the item and the game doesn't crash.

**Comment by snesrev** [comment]
I'm unable to reproduce this. Anyone else?

**Comment by JasonShearer** [comment]
I'm able to reproduce it on Windows 10. Instead of replacing the closed chest sprite with the open chest sprite, it's placing the open one below the closed one.

![zelda3_2022-09-23_02-19-25](https://user-images.githubusercontent.com/14334181/191930542-c9e7c705-58bf-4d5f-8349-ae6b85b220e3.png)

**Comment by snesrev** [comment]
And this is in the village of outcasts?

**Comment by JasonShearer** [comment]
Yes. FWIW, there's approximately three treasure chest games. The other two only contain three chests, however.

**Comment by snesrev** [comment]
Do you use any config options that are not the default options?

**Comment by snesrev** [comment]
Can you try the latest fix and see if it's the same? I still can't reproduce it though.

**Comment by snesrev** [comment]
Ok I found another weird looking thing.. Investigating

**Comment by JasonShearer** [comment]
Still bugged as of [e29fca2](https://github.com/snesrev/zelda3/commit/e29fca223ac5f93992736d20c5d3d68e1c955123).

**Comment by JasonShearer** [comment]
> Do you use any config options that are not the default options?

Sorry, just saw this. Same result with a default config.

![zelda3_2022-09-23_03-19-05](https://user-images.githubusercontent.com/14334181/191940545-5b441a51-1bfd-4d71-b328-5354d504be62.png)

**Comment by snesrev** [comment]
Try now?

**Comment by JasonShearer** [comment]
Working. 👍🏻

![zelda3_2022-09-23_03-26-38](https://user-images.githubusercontent.com/14334181/191941762-9b707c13-0e56-4599-a0b0-18b87c3b6d52.png)
