### ISSUE TITLE
add possibility of change key binding

### ISSUE THREAD

**Issue by Telev78** [snesrev/zelda3#12]
Hello,

Can you add the possibility to change the default key biding ?
Or detect if the keyboard is in azerty or qwerty ?

Regards

**Comment by yne** [comment]
Custom mapping added https://github.com/snesrev/zelda3/pull/21/commits/9eb7da61529e5026f3e85d3350740fa5a95dbd2c#diff-78f9666201f43a190a03011f3ca0e124cdbbd8daa0e6704521e121a3c3bf02a9

**Comment by snesrev** [comment]
I'm working on this.
