### ISSUE TITLE
exe doesn't run building from latest master (asset handling changes)

### ISSUE THREAD

**Issue by FitzRoyX** [snesrev/zelda3#122]
### Describe your bug here. And how to reproduce it.

nm

### What is your build target?

Windows

**Comment by aleczabaleta** [comment]
On a possibly related note, I am getting a merge conflict with zelda3.ini when using `git pull.` I therefore can't update and rebuild the exe

**Comment by VictorXPDE** [comment]
When i had to update to the latest master and was dealing with the same issue i just deleted the repo, cloned a brand new one and it worked just fine, for the .ini file merge conflict case, i do almost the same thing, delete the file and then ```git pull``` and just put my configs back to the file again. This may not be a good solution, but hey, it works.

**Comment by FitzRoyX** [comment]
I just realized that it runs if I don't move it out of the bin folder. Previously it worked if I moved the exe and dll to my thumb drive.

**Comment by krishean** [comment]
```
git fetch origin
git reset --hard origin/master
```

Is what fixed the merge conflict for me, without needing to delete the repo ( via https://stackoverflow.com/a/19864960 )

**Comment by snesrev** [comment]
The assets file is a new file that you also need. Is this still a bug?

**Comment by snesrev** [comment]
Perhaps it could be documented better
