### ISSUE TITLE
Windows 10 can't compile

### ISSUE THREAD

**Issue by EmeraldShield99** [snesrev/zelda3#135]
### Describe your bug here. And how to reproduce it.

I was able to extract and compile the resources successfully, and when i went to visual studio and built the solution, it Showed this in errors.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		NuGet Package restore failed for project Solution Items\zelda3: Unable to find version '2.0.5' of package 'sdl2'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'sdl2.2.0.5' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
. Please see Error List window for detailed warnings and errors.				

```

### What is your build target?

Windows

**Comment by xander-haj** [comment]
launch visual studio installer and verify you have everything shown in the picture installed.

![Screenshot 2022-10-03 08-32-20](https://user-images.githubusercontent.com/114783946/193590964-1990ee37-3f02-4c0f-9e73-bf3465143335.png)

or you can download the package from here https://www.nuget.org/packages/sdl2

**Comment by snesrev** [comment]
Seems to work for everyone else. Closing.
