### ISSUE TITLE
MSYS2 compile instructions

### ISSUE THREAD

**Issue by krishean** [snesrev/zelda3#136]
### Describe your bug here. And how to reproduce it.

With the latest commits adding in-app volume adjustment the MSYS2 compile instructions need to be updated, similarly to the way the tinycc build script was.

Instead of just `make`, using `CFLAGS="-DSYSTEM_VOLUME_MIXER_AVAILABLE=0" make` will now successfully build under the mingw32 or mingw64 environments. Without the addition of the CFLAGS parameter the build will fail with the error:
```
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ma
in.o:main.c:(.text+0x94f): undefined reference to `GetApplicationVolume'
C:/msys64/mingw32/bin/../lib/gcc/i686-w64-mingw32/12.2.0/../../../../i686-w64-mingw32/bin/ld.exe: ma
in.o:main.c:(.text+0x96b): undefined reference to `SetApplicationVolume'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:15: zelda3] Error 1
```

### What is your build target?

Windows

**Comment by DaBanana64** [comment]
![image](https://user-images.githubusercontent.com/82652849/193792065-da9a83e6-de5c-4b7f-92b4-356c0634f4ee.png)
Still the same error.

**Comment by krishean** [comment]
You might have to use `make clean` or `git clean -dfx` to clean up previous build artifacts before running make again. (If you use git clean you'll also have to add the rom file back to the tables directory and rebuild the dat file.)

**Comment by DaBanana64** [comment]
> You might have to use `make clean` or `git clean -dfx` to clean up previous build artifacts before running make again. (If you use git clean you'll also have to add the rom file back to the tables directory and rebuild the dat file. It will also remove any other files that are not in the repo such as saves, so you may want to back those up to a directory outside the repo first.)
> 
> Short version, try this: `make clean && CFLAGS="-DSYSTEM_VOLUME_MIXER_AVAILABLE=0" make`

![image](https://user-images.githubusercontent.com/82652849/193802938-7a121039-7225-4a7a-af10-ac8d1c66c426.png)
![image](https://user-images.githubusercontent.com/82652849/193802997-11d3149a-c23c-43cf-a26c-770988b70f4f.png)
Ok yeah it compiles now. This should be added to the Wiki.
