### ISSUE TITLE
Disabling EnhancedMode7 leads to broken map rendering

### ISSUE THREAD

**Issue by Rinnegatamante** [snesrev/zelda3#141]
### Describe your bug here. And how to reproduce it.

As the title says, disabling EnhancedMode7 breaks completely map rendering. Attached screenshots of it on RPI and on (WiP) PSVita port.

Vita:
![immagine](https://user-images.githubusercontent.com/9152710/194951970-3337a222-a5b8-4aa9-8e49-53e04f07551e.png)

RPI:
![immagine](https://user-images.githubusercontent.com/9152710/194951997-0d4d41f1-c185-45fb-a636-a22dee32de74.png)

### What is your build target?

Linux

**Comment by patrickmollohan** [comment]
Not able to reproduce on Manjaro/Arch Linux (x86). Might be an ARM-related issue.

**Comment by patrickmollohan** [comment]
Correction, can confirm with Manjaro/Arch on x86. Disabling EnhancedMode7 with the NewRenderer enabled causes visual glitches as shown above. Doesn't appear to impact the old renderer.
