### ISSUE TITLE
Zelda (G) Rom

### ISSUE THREAD

**Issue by agarnele** [snesrev/zelda3#144]
### Describe your bug here. And how to reproduce it.

i have the GERMAN Rom used (Hash: 030ff80d0087bca440094cd914c03da0aa199dc6edb9adfb43f1267e99fde45f) and try this - this ends this a error.... in line 96 & 102
The Legend of Zelda - A Link to the Past (G).zip

thx for this

(want a switch port)

### What is your build target?

Linux

**Comment by FitzRoyX** [comment]
Dude, remove that rom attachment, are you kidding? You need the USA rom btw.

**Comment by agarnele** [comment]
i wish the rom in german

**Comment by JasonShearer** [comment]
> i wish the rom in german

Under no circumstances should you ever link to Nintendo ROMs on a project like this. Remove it before you activate Nintendo's wrath.

**Comment by zerofalcon** [comment]
> ### Describe your bug here. And how to reproduce it.
> i have the GERMAN Rom used (Hash: 030ff80d0087bca440094cd914c03da0aa199dc6edb9adfb43f1267e99fde45f) and try this - this ends this a error.... in line 96 & 102 [The Legend of Zelda - A Link to the Past (G).zip](https://github.com/snesrev/zelda3/files/9761954/The.Legend.of.Zelda.-.A.Link.to.the.Past.G.zip)
> 
> thx for this
> 
> (want a switch port)
> 
> ### What is your build target?
> Linux

You cant attach copyrighted files! delete it as soon as posible

**Comment by snesrev** [comment]
You need the USA rom.
