### ISSUE TITLE
Can't throw boomerang diagonally south when Y is bound to certain Keypad keys

### ISSUE THREAD

**Issue by FitzRoyX** [snesrev/zelda3#149]
### Describe your bug here. And how to reproduce it.

This is an odd issue, not sure if it's SDL's fault or what. But with directionals bound to arrows, note the following behavior:

Bind Y to "Keypad 1": can't throw SW or SE
Bind Y to "Keypad 2": can't throw SE
Bind Y to "Keypad 3": no issues

I think it probably has something to do with the keypad also having arrows on it and maybe conflicting with the arrows?

### What is your build target?

Windows

**Comment by Nutzzz** [comment]
This is an issue with the design of your keyboard matrix (see a description of ghosting and masking issues [here](https://www.pcbheaven.com/wikipages/How_Key_Matrices_Works/)).  Not every keyboard's matrix is designed the same, but you'll find that for a given keyboard, some 3-key combinations will work, and some won't.  You can use [this website](https://keyboardtestt.com/) to do tests.  For example, I have the same problem with the combination down+left+A (throwing SW).

**Comment by FitzRoyX** [comment]
You're right, it behaves the same in two different emulators. Closing.
