### ISSUE TITLE
Error while running python scripts

### ISSUE THREAD

**Issue by krishean** [snesrev/zelda3#152]
### Describe your bug here. And how to reproduce it.

When running the `extract_resources.py` and `compile_resources.py` scripts with python 3.6.9 I get the following errors:

```
Traceback (most recent call last):
  File "extract_resources.py", line 4, in <module>
    import util
  File "tables/util.py", line 7
    def cache(user_function, /):
                             ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "compile_resources.py", line 3, in <module>
    import util
  File "tables/util.py", line 7
    def cache(user_function, /):
                             ^
SyntaxError: invalid syntax
```

The slash in the function def is new to me, so I looked it up: https://stackoverflow.com/questions/24735311/what-does-the-slash-mean-in-help-output

Using python 3.8 instead of 3.6.9 does indeed work as expected.

I think the easiest thing to do would be to add a note in readme.md that the minimum expected python version is 3.8 (Xubuntu 18.04 comes with 3.6.9 by default, but 3.8.0 is available in the repos with a simple apt-get. Also 3.6 is end of life, so there's also that.)

### What is your build target?

Linux

**Comment by QuarterSwede** [comment]
Same on macOS.
