### ISSUE TITLE
The music extraction python script doesn't seem to work

### ISSUE THREAD

**Issue by albert-softie** [snesrev/zelda3#16]
attempting to run `extract_music.py` produced this error for me:

```
[albert-softie@albert-softie-endeavouros tables]$ python extract_music.py
Traceback (most recent call last):
  File "/home/albert-softie/source/zelda3/tables/extract_music.py", line 463, in <module>
    song = sys.argv[1]
IndexError: list index out of range
[albert-softie@albert-softie-endeavouros tables]$
```
out of curiosity i attempted to pass the rom file directly to the python script, which resulted in a different error;
```
[albert-softie@albert-softie-endeavouros tables]$ python extract_music.py zelda3.sfc
Traceback (most recent call last):
  File "/home/albert-softie/source/zelda3/tables/extract_music.py", line 466, in <module>
    print_song(song, sys.stdout)
  File "/home/albert-softie/source/zelda3/tables/extract_music.py", line 271, in print_song
    get_song_list(0xd000, SONGS_IN_BANK)
NameError: name 'SONGS_IN_BANK' is not defined
[albert-softie@albert-softie-endeavouros tables]$ 
```

**Comment by sitton76** [comment]
I am not a dev on this project or anything, this is just a guess on my part, but considering that the `extract_resources` script imports `extract_music` I am guessing that `extract_music` is not intended to be ran by itself but instead called from `extract_resources`.

**Comment by yne** [comment]
The argv[1] is the name of the song, it can be `intro`, `lightworld`, `indoor` or `ending`

The path of the ROM is hardcoded

**Comment by snesrev** [comment]
e0afb3c203195cca81f5a01393f6625679ebf3c5
