### ISSUE TITLE
Shader error: Unknown key

### ISSUE THREAD

**Issue by JasonShearer** [snesrev/zelda3#162]
### Describe your bug here. And how to reproduce it.

Getting this error in the output window when using the crt-royale-kurozumi.glslp shader:

> shaders/presets/crt-royale-kurozumi.glslp:212: Unknown key 'texture_wrap_mode12'

I'm not sure if it's an issue with the shader or zelda3.

### What is your build target?

Windows

**Comment by snesrev** [comment]
Change
texture_wrap_mode12 = "clamp_to_edge"
to
wrap_mode12 = "clamp_to_edge"
