### ISSUE TITLE
Second Princess :lol:

### ISSUE THREAD

**Issue by ogamespec** [snesrev/zelda3#18]
If you save the princess early in the game and then return to her prison cell, another princess will appear.

![image](https://user-images.githubusercontent.com/5828819/186984684-4361c9d1-6a1e-4a89-bb30-fc648ba07276.png)

**Comment by Goodlyay** [comment]
Can confirm. Running with a rom to verify results in a crash and 
![image](https://user-images.githubusercontent.com/7892772/187015766-1a4d2334-19d9-4988-969d-4e9cece4ce1a.png)

**Comment by yne** [comment]
Same issue with the ambient BGM : the ambiant from the previous save is still playing.

**Comment by snesrev** [comment]
166acc4dfb5e27cff23b3672366b6979815f5dad
