### ISSUE TITLE
[FR] Lower OpenGL version requeriments so shaders can be used on the Raspberry Pi

### ISSUE THREAD

**Issue by vanfanel** [snesrev/zelda3#189]
### What feature do you want to get added? And how it will work?

Hi!

I have built this Zelda 3 reimplementation and I am truly amazed. No words on how incredible this plays and looks, and the value of this: the best action RPG ever made is now compilable...everywhere!

So, it saddens me a bit that it requires OpenGL 3.3 to work.
OpenGL 2.x should be enough, even OpenGL_ES2 will be enough: most of the shaders work perfectly on the Raspberry Pi in RetroArch, so those OpenGL versions are enough and would let us use the shaders on the Pi.
This game's graphics heavily depend on CRT effects to look "as intended".

I have been experimenting myself: in opengl.c, these calls set the GL version for the rendering context:

```
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 3);
```

But even after doing something like this for Raspberry Pi compatibility:

```
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 2);
SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 1);
```
...the game still complains that it needs OpenGL 3.3, which is (I think) not true.

So, can it be lowered, please? Thanks!

**Comment by vanfanel** [comment]
This block:
https://github.com/snesrev/zelda3/blob/91d771ecc4532e4e40995b133edd9d82a39d61ac/opengl.c#L215
...could be made into:
```
void OpenGLRenderer_Create(struct RendererFuncs *funcs) {
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 2);
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 1);
```
...because GLES 2 is enough for many of those shaders as I said.

Also, I have seen that OpenGL version detection is done at:
https://github.com/snesrev/zelda3/blob/91d771ecc4532e4e40995b133edd9d82a39d61ac/opengl.c#L45

But further changes are needed, which are far above my head.

**Comment by vanfanel** [comment]
More on this.

I got this:
https://github.com/snesrev/zelda3/blob/91d771ecc4532e4e40995b133edd9d82a39d61ac/opengl.c#L215

Into this:
```
void OpenGLRenderer_Create(struct RendererFuncs *funcs) {
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_PROFILE_MASK, SDL_GL_CONTEXT_PROFILE_ES);
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_MAJOR_VERSION, 3);
  SDL_GL_SetAttribute(SDL_GL_CONTEXT_MINOR_VERSION, 1);
```

Commented out this:
https://github.com/snesrev/zelda3/blob/91d771ecc4532e4e40995b133edd9d82a39d61ac/opengl.c#L45

Made this:
https://github.com/snesrev/zelda3/blob/91d771ecc4532e4e40995b133edd9d82a39d61ac/opengl.c#L83
..into this:
`const GLchar *vs_code = "#version 310 es\n" CODE(`

Made this:
https://github.com/snesrev/zelda3/blob/91d771ecc4532e4e40995b133edd9d82a39d61ac/opengl.c#L106
...into this:
`const GLchar *fs_code = "#version 330 core\n" CODE(`

...and now I get NO errors at all, but sadly only a black screen.

**Comment by vanfanel** [comment]
Moving the context to GLES 3.1 seems to be causing some problem with glTexImage2D here:

```
187         glTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, g_draw_width, g_draw_height, 0, GL_BGRA, GL_UNSIGNED_INT_8_8_8_8_REV, g_screen_buffer);
(gdb) n
190       glClearColor(0.0f, 0.0f, 0.0f, 1.0f);
(gdb) p/x (GLint)glGetError()
$27 = 0x502
```

**Comment by vanfanel** [comment]
Oh, it seems that GLES's glTexImage2D() doesn't support the **GL_UNSIGNED_INT_8_8_8_8_REV** format that is used on the screen buffer! :(
https://registry.khronos.org/OpenGL-Refpages/es3.0/html/glTexImage2D.xhtml

**Comment by vanfanel** [comment]
Changing `GL_UNSIGNED_INT_8_8_8_8_REV`  to `GL_UNSIGNED_BYTE` , the game works perfectly well on GLES 3.1 on the Raspberry Pi with shaders! Yay!

**Comment by vanfanel** [comment]
To prevent the GLSL shader compiler from complaining when compiling some shaders for GLES, I also had to change this:
https://github.com/snesrev/zelda3/blob/91d771ecc4532e4e40995b133edd9d82a39d61ac/glsl_shader.c#L217
..into this:
`static const char kFragmentPrefix[] = "#define FRAGMENT\n#define PARAMETER_UNIFORM\nprecision mediump float;\n";`

Having this game (one of the best videogames in history, period) with Fakelottes shader running natively on ARM sbcs on Wayland is simply amazing!
PR coming soon...

**Comment by vanfanel** [comment]
This PR fixes the issue:
https://github.com/snesrev/zelda3/pull/192

**Comment by retropieuser** [comment]
I'm finding on my pi 4 I get this error when attempting to build:- 

`pi@retropie:~/zelda3 $ CFLAGS="-DUSE_GLES=1" make
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 util.c -o util.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 zelda_cpu_infra.c -o zelda_cpu_infra.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 config.c -o config.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 sprite_main.c -o sprite_main.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 tile_detect.c -o tile_detect.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 dungeon.c -o dungeon.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 overworld.c -o overworld.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 player.c -o player.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 nmi.c -o nmi.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 poly.c -o poly.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 sprite.c -o sprite.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 misc.c -o misc.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 select_file.c -o select_file.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 audio.c -o audio.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 opengl.c -o opengl.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 player_oam.c -o player_oam.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 attract.c -o attract.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 tagalong.c -o tagalong.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 zelda_rtl.c -o zelda_rtl.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 ending.c -o ending.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 spc_player.c -o spc_player.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 main.c -o main.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 overlord.c -o overlord.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 hud.c -o hud.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 glsl_shader.c -o glsl_shader.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 ancilla.c -o ancilla.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 messaging.c -o messaging.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 load_gfx.c -o load_gfx.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 snes/dsp.c -o snes/dsp.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 snes/spc.c -o snes/spc.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 snes/ppu.c -o snes/ppu.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 snes/snes_other.c -o snes/snes_other.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 snes/cart.c -o snes/cart.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 snes/snes.c -o snes/snes.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 snes/cpu.c -o snes/cpu.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 snes/apu.c -o snes/apu.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 snes/dma.c -o snes/dma.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 snes/input.c -o snes/input.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 snes/tracing.c -o snes/tracing.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 third_party/gl_core/gl_core_3_1.c -o third_party/gl_core/gl_core_3_1.o
cc -c -DUSE_GLES=1 -I/usr/include/SDL2 -D_REENTRANT -DSYSTEM_VOLUME_MIXER_AVAILABLE=0 third_party/opus-1.3.1-stripped/opus_decoder_amalgam.c -o third_party/opus-1.3.1-stripped/opus_decoder_amalgam.o
In file included from third_party/opus-1.3.1-stripped/opus_decoder_amalgam.c:18:
third_party/opus-1.3.1-stripped/opus_decoder.c:37:10: note: #pragma message: You appear to be compiling without optimization, if so opus will be very slow.
 # pragma message "You appear to be compiling without optimization, if so opus will be very slow."
          ^~~~~~~
cc util.o zelda_cpu_infra.o config.o sprite_main.o tile_detect.o dungeon.o overworld.o player.o nmi.o poly.o sprite.o misc.o select_file.o audio.o opengl.o player_oam.o attract.o tagalong.o zelda_rtl.o ending.o spc_player.o main.o overlord.o hud.o glsl_shader.o ancilla.o messaging.o load_gfx.o snes/dsp.o snes/spc.o snes/ppu.o snes/snes_other.o snes/cart.o snes/snes.o snes/cpu.o snes/apu.o snes/dma.o snes/input.o snes/tracing.o third_party/gl_core/gl_core_3_1.o third_party/opus-1.3.1-stripped/opus_decoder_amalgam.o -o zelda3  -L/usr/lib/arm-linux-gnueabihf -lSDL2 -lm
Extracting game resources
Traceback (most recent call last):
  File "extract_resources.py", line 538, in <module>
    main()
  File "extract_resources.py", line 531, in main
    print_all_text_stuff()
  File "extract_resources.py", line 522, in print_all_text_stuff
    print_all_overworld_areas()
  File "extract_resources.py", line 240, in print_all_overworld_areas
    print_overworld_area(i)
  File "extract_resources.py", line 232, in print_overworld_area
    s = yaml.dump(y, default_flow_style=None, sort_keys=False)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 200, in dump
    return dump_all([data], stream, Dumper=Dumper, **kwds)
TypeError: dump_all() got an unexpected keyword argument 'sort_keys'
make: *** [Makefile:34: tables/dialogue.txt] Error 1`

Any ideas?

**Comment by vanfanel** [comment]
> I'm finding on my pi 4 I get this error when attempting to build:-
> 
> https://pastebin.com/EU1rnRZ9
> 
> Any ideas? I have these:-
> 
> `pi@retropie:~/zelda3 $ python3 --version Python 3.7.3 pi@retropie:~/zelda3 $ pip3 --version pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7) pi@retropie:~/zelda3 $ `

That error has nothing to do with OpenGL. Please move this to a different issue.

**Comment by arczi84** [comment]
Really it requires OGL 3.3 ?! 
Look at these fan made Zelda clones. Not only  those 4 games doesn't use GL at all but need only SDL1!
http://www.zeldaroth.fr/us/

**Comment by vanfanel** [comment]
> Really it requires OGL 3.3 ?! Look at these fan made Zelda clones. Not only those 4 games doesn't use GL at all but need only SDL1! http://www.zeldaroth.fr/us/

That comparision makes no sense at all, because those Zelda clones don't use shaders (hence they look like s**t on modern displays).

Can you guys stop posting nonsense on this thread, please?
