### ISSUE TITLE
Unable to build on a 32 bit build raspberry pi 4

### ISSUE THREAD

**Issue by retropieuser** [snesrev/zelda3#194]
### Describe your bug here. And how to reproduce it.

I'm finding on my pi 4 I get this error when attempting to build:-

https://pastebin.com/EU1rnRZ9

Any ideas? I have these:-

```
pi@retropie:~/zelda3 $ python3 --version 
Python 3.7.3 
pi@retropie:~/zelda3 $ pip3 --version 
pip 18.1 from /usr/lib/python3/dist-packages/pip (python 3.7) 
pi@retropie:~/zelda3 $ 
```

As you can see I'm running from Retropie which runs on Raspberry Pi OS Lite Buster at a 32 bit rather than 64 bit architecture. I'm not sure if that's causing me the issues? As the error appears to be python related?

### What is your build target?

Raspberry Pi

**Comment by fac3l3ss79** [comment]
I confirm the issue. It does compile properly in raspberry OS 64 bit tough.

**Comment by fac3l3ss79** [comment]
Ok, after trying again to compile on a 32 bit build of raspberry pi OS, I don't think this is a bug. It does compile if you point out python path. Just type on the terminal "export PATH=”$PATH:/usr/bin/python3" (without the quotes) before compiling and everything will be ok.
