### ISSUE TITLE
Allow whitespec and comments before #version directive in shaders as described in spec

### ISSUE THREAD

**Issue by noidexe** [snesrev/zelda3#197]
### Describe your bug here. And how to reproduce it.

Trying to use hyllian-glow I get the following error:
```
Error compiling vertex shader in file 'shaders/hyllian/crt-hyllian-glow/crt-hyllian-glow.glsl':
0(29) : error C0204: version directive must be first statement and may not be repeated
```
This is due to comments appearing before #version 120.

According to the [glsl documentaion](https://www.khronos.org/opengl/wiki/Core_Language_(GLSL)) whitespace and comments are allowed before version directive, so this error shouldn't happen

An easy workaround is opening the glsl file and moving #version to the top of the file

### What is your build target?

Linux

**Comment by DonelBueno** [comment]
Sorry for the question, but how can you use shaders? I tried creating a folder called "shaders" and puting a .glsl shader there, but it didn't work.

The game always runs in D3D9, how can I make it run in OpenGL?

**Comment by noidexe** [comment]
@DonelBueno you have to edit the .ini file
Path to shader is here: https://github.com/snesrev/zelda3/blob/master/zelda3.ini#L55
To use OpenGL replace `SDL` with `OpenGL` here: https://github.com/snesrev/zelda3/blob/master/zelda3.ini#L47

**Comment by DonelBueno** [comment]
My .ini was outdated, got it from the release build. Thanks!
