### ISSUE TITLE
Crystal cutscene refill lag

### ISSUE THREAD

**Issue by Ninban** [snesrev/zelda3#20]
On every crystal cutscene refill, there was some big lag as the hearts and magic meter were counting up, that last until the "ding" at the end of the spinning animation.

Like my other issue, I'll retry by next Saturday with the ROM running along in hope of being able to get more details.

https://clips.twitch.tv/CrackyBrightTrollMingLee-McLRWoakEq9RY4Lr

**Comment by snesrev** [comment]
Can you clarify what's wrong and/or show a video what it's supposed to look like?

**Comment by Ninban** [comment]
You can compare the end of my clip with this video I found on youtube at the timestamp: https://youtu.be/KT6nxj6fr8c?t=604
You should see the difference very quickly. This happens in all of the 7 crystal cutscenes.

**Comment by Ninban** [comment]
I also think the text seems slower but wasn't sure to be honest. I guess since we both agree it probably is.
The faster crystal spin I just assumed it was from "reduced lag" due to not running on SNES hardware, like many other instances of lag in the game that go much faster on this port.

The most obvious is the end of the cutscene, with the heart/magic refill and the spin attack.

**Comment by keatongreve** [comment]
I believe the text speed can be sped up through button pressing. here's another playthrough where the text speed seems to be slower, matching the Twitch clip: https://youtu.be/xf2IO7P5DVA?t=11363 (if timecode isn't working, go to 3:09:00)
