### ISSUE TITLE
Disable the funky epileptic rainbow color-o-rama on the title screen

### ISSUE THREAD

**Issue by shakeyourbunny** [snesrev/zelda3#205]
### Describe your bug here. And how to reproduce it.

Is it possible to disable the funky rainbow epileptic full screen color banding on the title card screen?

I'd really want to share this with a friend of mine, but he has a known history of epilepsis and even for me it is hard to digest.

Thank you.

### What is your build target?

Windows

**Comment by FitzRoyX** [comment]
A massive amount of old video games have flashing effects and came with epilepsy warnings. It's impossible to go back and redesign everything to not have them, that is mod material. It's not just the title screen here, the ether spell does it, some cutscenes probably do it. Look away or find a different game.

**Comment by shakeyourbunny** [comment]
Hm, I personally don't mind these flashes, but a friend of mine, who already suffered two epilepsy attacks does.

I don't want to be responsible for a third one, so I'll guess, I'll warn my friend about that and don't recommend the game. 

Please don't take that personally, the work you have done is amazing and fascinating, keep up the good work!

**Comment by DPS2004** [comment]
I disagree, this is something thats worth pursuing. [The 3DS Virtual Console version](https://youtu.be/QJCku-F_uR4?t=32) was able to diminish flashing effects, so why can't we?

**Comment by shakeyourbunny** [comment]
I would really appreciate this, perhaps for sake of faithful implementation, put a switch in the ini file, like 

````
dim_flashes=1
````

for at least reducing or removing the effect would be neat.

**Comment by DPS2004** [comment]
update on this, [found some documentation](https://www.romhacking.net/forum/index.php?topic=23021.0) on what exact code changes the Virtual Console versions have. Will look into how to add it as an option
