### ISSUE TITLE
Doesnt Work for me on mac

### ISSUE THREAD

**Issue by AYMAAN69** [snesrev/zelda3#209]
### Describe your bug here. And how to reproduce it.

It says somethign about unicode and after compiling nothing happens . i try to run the executable but it shows an error 
:
SyntaxError: Non-UTF-8 code starting with '\xcf' in file /Users/aymaan/zelda3/zelda3 on line 2, but no encoding declared; see https://python.org/dev/peps/pep-0263/ for details

### What is your build target?

Mac

**Comment by bolshoytoster** [comment]
@AYMAAN69 how are you running the executable? It looks like you're trying to run it with python.

Try just running `/Users/aymaan/zelda3/zelda3` in the terminal.

**Comment by AYMAAN69** [comment]
> @AYMAAN69 how are you running the executable? It looks like you're trying to run it with python.
> 
> Try just running `/Users/aymaan/zelda3/zelda3` in the terminal.

ok i did that and now i get this error 

Warning: Unable to read config file zelda3.ini
Error: Failed to read zelda3_assets.dat. Please see the README for information about how you get this file.

**Comment by TheAdmiral** [comment]
@AYMAAN69 try the following:

1. Open Terminal
2. Run `cd  /Users/aymaan/zelda3/`
3. Run `./zelda3`

The reason for this is that the zelda3 executable may be looking in whatever is your current working directory for the config file, so you need to use the `cd` command to switch to the directory containing the config file before running the executable.

**Comment by AYMAAN69** [comment]
it works thank you
