### ISSUE TITLE
Save / Load

### ISSUE THREAD

**Issue by Monkeycat-nl** [snesrev/zelda3#211]
### What feature do you want to get added? And how it will work?

It is very confusing how to save your progress...

I have to die to save... and it loads to predefined locations instead where I was...

I got the seconds pendent... and since it was already very late and I did not know how to save. I let myself die to have the save and continue option.

Next morning loading it up again... It restores to a state where I died hours ago with only one pendent.

It would be nice to have to have some instructions how to properly save a game.

maybe nice to have a quick save/load option with keys who are NOT next to each other (and uses shift/ctrl/alt combo, see my other issue post about 1...9)

**Comment by impeeza** [comment]
That is the way the original game works, you can save in any time and place, but when restoring the game ask where you want to start from.

**Comment by Monkeycat-nl** [comment]
i get that...

>That is the way the original game works, you can save in any time and place, but when restoring the game ask where you want to start from.

i have no idea how to do that... currently i have to die...

>On Zelda3 you can use save/restore function to get back any where you want

so how do i do that?

as a noob... instructions are unclear... there is nothing in the readme.me how to...

**Comment by FitzRoyX** [comment]
The way you save in this game is to press Select. Do you know what your Select key is? It is Right Shift by default, it says right there in the ini.

**Comment by snesrev** [comment]
Try again with master and reopen if still not working.
