### ISSUE TITLE
Pressing (accidentally) 1, 2, ... 9 will move link to another location ruining current play

### ISSUE THREAD

**Issue by Monkeycat-nl** [snesrev/zelda3#213]
### What feature do you want to get added? And how it will work?

Maybe make it shift-(1..9) instead...

Was really annoying to exit and reload my last save and replay (a lot) because I was in an unknown location because I accidentally pressed the wrong key...

If the user has to press two keys at once... those accidents will not happen...

note 1: I was pressing 'w' alot which is very very close to '2' and '3' to restore my health.. :-) 
note 2: maybe also add something that health just stays full... since I am not the 11 year old with all the time in the world
and the determination to get past certain areas with difficult enemies ;-)

**Comment by JasonShearer** [comment]
You can change this yourself in the zelda3.ini by changing this line:

`LoadRef = 1,2,3,4,5,6,7,8,9,0,-,=,Backspace`

To something like this:

`LoadRef = Shift+1,Shift+2,Shift+3,Shift+4,Shift+5,Shift+6,Shift+7,Shift+8,Shift+9,Shift+0,Shift+-,Shift+=,Shift+Backspace`

But you make a good point. It should probably require two keys by default.

**Comment by FitzRoyX** [comment]
Accidentally hitting proximity keys has always been a problem for the WASD control scheme. The current method is fast for testing. There are many options here for OP:

1) Use a gamepad
2) Rebind to Arrow keys for move and Keypad # for buttons
3) Go into the ini file and delete all the LoadRef bindings

**Comment by Monkeycat-nl** [comment]
Uhm... default does not use WASD.
Not all people have a gamepad or are that technical.
And by prioritizing testers you make it a problem as the main users.

a little bit user (noob) friendly polish...

i looked into zelda3.ini those options should be in a osd menu... 
(also mute options is missing... there is volume up and down but no mute)

but man, fun to rediscover what a great game this is... 4x older ;)
enjoy the heck out of it playing it ;) 

---- 8< ----

currently, how do i change the pixel shader or the aspect ratio??? i have no idea... not in the readme and not in the wiki. so you are either technical... and understand that the ini file is important and you have located it or you stuck, like my son waiting for me to be the wizard :-).
