### ISSUE TITLE
Remapping controls

### ISSUE THREAD

**Issue by edbefee3-3888-462a-9411-741b7e9eb54e** [snesrev/zelda3#220]
### What feature do you want to get added? And how it will work?

I think you should be able to remap the controls, since sometimes the default ones just don't make sense (eg. A/B and X/Y being mapped wrong on Switch controllers)
I don't know where you could put that menu, though

**Comment by Kryptortio** [comment]
You can already do that, just open [zelda3.ini](https://github.com/snesrev/zelda3/blob/master/zelda3.ini#L133) in notepad.

**Comment by snesrev** [comment]
Edit zelda3.ini
