### ISSUE TITLE
Support for French Canadian Rom

### ISSUE THREAD

**Issue by FredericVincent0** [snesrev/zelda3#234]
### What feature do you want to get added? And how it will work?

do you plan to support canadian french rom or any other rom region???

**Comment by DPS2004** [comment]
The extraction scripts are currently built to only work with the USA rom, adding support for other roms would be a lot of effort because the data will be stored in slightly different places for all of them.

**Comment by Thpwg** [comment]
Hello. I am a novice in your field, but I would like to ask a question. If the port is only compatible with the US version of the game, is it possible that it could also be compatible if the US game is patched into French with a fan translation? Thank you.

**Comment by FredericVincent0** [comment]
I think it will be possible but im not sure im not an expert in this im at
the same level as you

Le jeu. 27 nov. 2025, 05 h 04, Threepwang ***@***.***> a
écrit :

**Comment by Thpwg** [comment]
> I think it will be possible but im not sure im not an expert in this im at
> the same level as you
> 
> Le jeu. 27 nov. 2025, 05 h 04, Threepwang ***@***.***> a
> écrit :
> […](#)

Salut FredericVincent0,

Il est possible de localiser le jeu en français et en français du Canada.
Regarde ce lien : [Multi-Language Support](https://github.com/snesrev/zelda3/wiki/2.-Cloning-and-Setup#multi-language-support)

Si tu n'y arrives pas, inscris-toi sur le forum Abandonware France et cherche le sujet "Zelda sur PC : Que sais-je ?". Je t’aiderai :)

**Comment by FredericVincent0** [comment]
Ok merci 🥰

Le mar. 6 janv. 2026, 21 h 43, Threepwang ***@***.***> a
écrit :
