### ISSUE TITLE
Flatpak

### ISSUE THREAD

**Issue by heroesiiifan** [snesrev/zelda3#239]
### What feature do you want to get added? And how it will work?

I'm currently preparing a Flatpak release at Flathub:
https://github.com/flathub/flathub/pull/4035

Can installed & launched with:
```
sudo apt install flatpak-builder
flatpak install flathub org.freedesktop.Platform//22.08 org.freedesktop.Sdk//22.08
git clone https://github.com/heroesiiifan/flathub.git --branch org.snesrev.Zelda3
cd flathub/
flatpak-builder --user --install --force-clean build-dir io.github.snesrev.Zelda3.yml
flatpak run io.github.snesrev.Zelda3
```

With a start script. The ROM is only converted at the first start.

It is possible to upstream the desktop, icon and appstream file from there?

**Comment by heroesiiifan** [comment]
merged

**Comment by sofakng** [comment]
Can this be updated to v0.3?

Thanks!
