### ISSUE TITLE
Can't build on windows, some headers can't be found

### ISSUE THREAD

**Issue by oniliste** [snesrev/zelda3#25]
![image](https://user-images.githubusercontent.com/7047089/187322084-ed1b9e69-ad80-43aa-9ea6-1d7873c819cb.png)

**Comment by keatongreve** [comment]
Did you generate the files from the python scripts (see README)?

**Comment by oniliste** [comment]
I have skipped this section🤣，but It's still failed, the script report errors below:

PS D:\Code\zelda3\tables> python extract_resources.py
Traceback (most recent call last):
  File "D:\Code\zelda3\tables\extract_resources.py", line 13, in <module>
    ROM = util.LoadedRom()
  File "D:\Code\zelda3\tables\util.py", line 7, in __init__
    self.ROM = open(name, 'rb').read()
FileNotFoundError: [Errno 2] No such file or directory: 'zelda3.sfc'

**Comment by oniliste** [comment]
I did not copy the rom
