### ISSUE TITLE
Fat Fairy does not appear early.

### ISSUE THREAD

**Issue by TimmyP777** [snesrev/zelda3#264]
### Describe your bug here. And how to reproduce it.

Beaten Misery Mire and Ice Palace first, to get upgraded equipment before the rest. Got the red bomb. Does not bomb wall to get to fat fairy. The bomb goes off, but does not break wall.

### What is your build target?

Windows

**Comment by DPS2004** [comment]
This bug was fixed a long time ago, please build a newer version, following the instructions in the Readme

**Comment by TimmyP777** [comment]
None of this shit works. Python does not work add to path in windows 10.
What a joke.

**Comment by TimmyP777** [comment]
There is no way to build this game for yourself, at all on some systems. Thanks for removing precompiled binaries yesterday.

Spent the entire day on this. Wasted. Python does not install as path on windows 10 on ryzen. The tool does not download dependencies.

This is not available for some.

**Comment by Dewey-Wilkerson** [comment]
> There is no way to build this game for yourself, at all on some systems. Thanks for removing precompiled binaries yesterday.
> 
> Spent the entire day on this. Wasted. Python does not install as path on windows 10 on ryzen. The tool does not download dependencies.
> 
> This is not available for some.

No, you're just a childish, petulant moron with no problem solving skills.  I literally set up a brand new install of Win10/11 last week, without any backups of prior installs, and built this perfectly fine.  Hell, I didn't even bother installing WSL2 to use python like I normally do, I just went straight for the VS installer.  You just happened to miss a checkbox, and are too lazy to learn how to add things to PATH yourself.  Stop polluting this thread with your crap.  Your tone is uncalled for and childish.  Your issue is borne of your own failures, and not the failures of the repo or the code within.  It's okay to say you don't understand something, instead of lashing out and blaming the thing for not working the way you thought.  I'd explain it more in depth, but I have nether the time nor crayons required to explain it simply enough that you'd understand.

**Comment by TimmyP777** [comment]
Fixed! You HAVE to use the readme instructions in certain buyild
environemnts. sorry for my tone, but its very frustrating i just spent a
ton of time on this

Wasnt aware the readme had instructions so different, that they work and
the ones posted on the github page do not!

**Comment by Dewey-Wilkerson** [comment]
Wow.... Read a file called "read me"... so uhh... so unintuitive.  If only we had a way to mark that you should read that file.  Maybe call it "read me" or some-- Hey wait a minute.

**Comment by TimmyP777** [comment]
Yeah vs instructions on the main page labeled "Compiling on Windows with TCC (1mb Tiny C Compiler)" that do not work.

Look I spent WAY more time on this than probably ANYONE. As soon as I read the readme, which to his credit, OP did say, I had it in seconds... I just figured that both worked because thats how it usually is.

Its an honest mistake but I felt like I was gonna go nuts. Nobody else plays fairy first like me. NOBODY.

**Comment by TimmyP777** [comment]
and real quick.

It might be using that gui tool, which now freezes at dependency install (reported on its github) causing something to happen when using the official repo github page instructions.

**Comment by Dewey-Wilkerson** [comment]
> Look I spent WAY more time on this than probably ANYONE.

You sure did; people who put thought into the things they do would see something wrong, and go "hmm... lemme go check the documentation again and see if I missed anything" rather than just screaming about it and blaming everyone else.

**Comment by TimmyP777** [comment]
Nobody does that when instructions are posted on the main page. This is
ridiculous. I found this problem for you. I apologize I was at the end of
my rope... but those instructions shouldn't even exist!

"Lemme go check the documentation..." Its a README. How long have you been
doing this? For problems like this, NOBODY would just check the readme. Why
would official instructions not work?

Go ahead and run through them, you will see that those instructions are
IMPOSSIBLE! I had to be the one to suffer, AND I apologize. Now you (or
whoever) can fix them.

PS: There is a script missing.

**Comment by DPS2004** [comment]
@TimmyP777 if you feel so strongly about the instructions being slightly incorrect, make a pr about it instead of fighting with strangers on the Internet

**Comment by TimmyP777** [comment]
Im not fighting with anyone. The instructions are not *slightly* incorrect.
They are not-usable. Wtf do you think I am trying to say?

Look at the instructions on the site, and look at the instructions in the
readme.md. Specifically the "compiling with TCC section." See anything
thats... i dont know... kinda formatted the same, but if you look close it
says something completely different? And only that works?

Didnt think so. Glad I could catch you up on this non issue for me.

**Comment by DPS2004** [comment]
Ok, then make a pr for the completely unusable instructions that, by my estimates, hundreds of people have managed to follow perfectly ¯\_(ツ)_/¯

**Comment by impeeza** [comment]
lot of us have build the latest versions without problem.

If you like here is a summary of commands to build using MSYS2 on Windows:


**TARGET WINDOWS BINARY:**

```
pacman -Sy --needed --noconfirm git make mingw-w64-x86_64-python  mingw-w64-x86_64-python3-pillow mingw-w64-x86_64-python-yaml mingw-w64-x86_64-gcc mingw-w64-x86_64-SDL2

cd ~
git clone --recursive https://github.com/snesrev/zelda3
cd ~/zelda3/
#YOU NEED TO copy ROM to ~/zelda3/tables/zelda3.sfc
make -j$(nproc)
```


**TARGET SWITCH BINARY:**
YOU NEED DEVKITPRO WORKING ON YOUR MSYS2 SETUP (https://devkitpro.org/wiki/devkitPro_pacman)
```

pacman -Sy --needed --noconfirm git make pkg-config switch-dev switch-sdl2 switch-tools switch-pkg-config mingw-w64-x86_64-python mingw-w64-x86_64-python3-pillow mingw-w64-x86_64-python-yaml


git clone --recursive https://github.com/snesrev/zelda3
#copy ROM to ~/zelda3/tables/zelda3.sfc
cp "h:\Emuladores\Nintendo Switch\HomeBrew\The Legend of Zelda - A Link to the Past\_ROM\zelda3.sfc" ~/zelda3/tables/
cd ~/zelda3/tables/
python extract_resources.py
python compile_resources.py


cd ~/zelda3/platform/switch/

export DEVKITPRO=/opt/devkitpro
export DEVKITARM=/opt/devkitpro/devkitARM
export DEVKITPPC=/opt/devkitpro/devkitPPC
export PATH=${DEVKITPRO}/tools/bin:$PATH

make -j$(nproc)
```

IT'S EASY
