### ISSUE TITLE
Wonky d-pad when playing with a DualShock 4 controller?

### ISSUE THREAD

**Issue by Kombatologist** [snesrev/zelda3#40]
I'm playing with a DualShock 4 controller (wired via USB) and getting some wonky behavior with the d-pad. When moving Link, he'll randomly stop moving, as if the d-pad is no longer registering. The analog doesn't seem to have any issues, however. It's also probably worth mentioning that this happens with or without a controller mapper like DS4Windows.

**Comment by snesrev** [comment]
It doesn't happen in other games at all?

Perhaps it's related to input events from the analog joystick? Does the dpad stop working if you touch the analog?

**Comment by Kombatologist** [comment]
Doesn't happen in other games, no. I tried two different DS4 controllers and same result. Granted, DS4 controllers are notorious for developing stick drift, so I thought maybe it was the analog stick canceling out the d-pad input. But even with the dead zones set to max in DS4Windows, it still wonks out. In fact, the behavior is significantly worse when the sticks are set to max (1.00) dead zone for some strange reason. At half (0.50), it happens occasionally. At default (0.08-ish?), it seems to happen every few seconds. I'm not noticing any phantom inputs, but don't quote me on that.
