### ISSUE TITLE
NuGet Package restore failed

### ISSUE THREAD

**Issue by rdmcintee** [snesrev/zelda3#44]
Severity	Code	Description	Project	File	Line	Suppression State
Error		NuGet Package restore failed for project zelda3: Unable to find version '2.0.5' of package 'sdl2'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'sdl2.2.0.5' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
. Please see Error List window for detailed warnings and errors.				

Severity	Code	Description	Project	File	Line	Suppression State
Error		NuGet Package restore failed for project zelda3: Unable to find version '2.0.5' of package 'sdl2.redist'.
  C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\: Package 'sdl2.redist.2.0.5' is not found on source 'C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\'.
. Please see Error List window for detailed warnings and errors.				

Severity	Code	Description	Project	File	Line	Suppression State
Error		This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is packages\sdl2.redist.2.0.5\build\native\sdl2.redist.targets.	zelda3	C:\Users\rdmci\source\repos\zelda3\zelda3.vcxproj	251	

![image](https://user-images.githubusercontent.com/112129719/188052469-db7d90ae-a4c8-41f2-b9fe-2747614bf901.png)

**Comment by keatongreve** [comment]
<img width="887" alt="Screen Shot 2022-09-01 at 11 01 14 PM" src="https://user-images.githubusercontent.com/596193/188069124-adb24109-07e8-4e42-b2b8-e1f8eb4b33de.png">

**Comment by rdmcintee** [comment]
> <img alt="Screen Shot 2022-09-01 at 11 01 14 PM" width="887" src="https://user-images.githubusercontent.com/596193/188069124-adb24109-07e8-4e42-b2b8-e1f8eb4b33de.png">

I did that but it accomplished nothing

**Comment by rdmcintee** [comment]
my package manager was missing nuget as a source

![image](https://user-images.githubusercontent.com/112129719/188196963-5c9bc51d-ed8b-4f8a-9159-e7070757b05b.png)
