### ISSUE TITLE
Fullscreen is broken on Manjaro Linux

### ISSUE THREAD

**Issue by CirkuitBreaker** [snesrev/zelda3#45]
when I fullscreen the game, my entire screen glitches out except for the top left corner of the screen, where the game is running in normal size.

OS: Manjaro Linux
GPU: AMD RX 5700
CPU: AMD Ryzen 5 3600
window manager: kwin
display server: X11

**Comment by snesrev** [comment]
It seems to work on Windows and on my Linux installation (running on Windows) so I don't know.

**Comment by snesrev** [comment]
Is this bug fixed now too?

**Comment by CirkuitBreaker** [comment]
> Is this bug fixed now too?

ish. Alt+Enter "fullscreens" the game, but it only runs in the top left corner at native size. Fullscreening using my window manager (Alt+F3 -> More Actions -> Fullscreen) works perfectly. There is no garbage all over my screen in either case.

**Comment by 1985a** [comment]
it works at my end in the current git master 08d6dad

**Comment by snesrev** [comment]
I close this bug cause it's probably something messed up with that linux distro. Please reopen if things change.
