### ISSUE TITLE
Alt + Enter not triggering fullscreen on Windows 10

### ISSUE THREAD

**Issue by rdmcintee** [snesrev/zelda3#49]
Title says it all, let me know what details you need from me

**Comment by FitzRoyX** [comment]
The default fullscreen hotkey is ctrl+return when the ini file is not present in the exe directory. When it is present, it becomes alt+return.

**Comment by rdmcintee** [comment]
> The default fullscreen hotkey is ctrl+return when the ini file is not present in the exe directory. When it is present, it becomes alt+return.

gotcha, thank you
