### ISSUE TITLE
Fullscreen issues in Linux

### ISSUE THREAD

**Issue by patrickmollohan** [snesrev/zelda3#50]
As noted by #43 and #45, there are issues with fullscreen in Linux. Running with the latest commits, garbage gets shown on the sides of the screen, like this:
![Screenshot from 2022-09-02 15-32-43](https://user-images.githubusercontent.com/14967142/188225237-eab4aa46-9e66-44ef-a1ca-361e5c865c93.png)
Commit c9e2b4ced16118446f6901a4a3026bc06aa90f5e falsely marked #43 as fixed and the PR was closed. Unless there is something I'm missing, the config file does not address any fullscreen issue in Linux. #43 should have been accepted or an alternative proposed.

**Comment by snesrev** [comment]
Is it fixed now?

**Comment by patrickmollohan** [comment]
@snesrev yup, it's fixed now!
