### ISSUE TITLE
MSYS2 Support

### ISSUE THREAD

**Issue by Fancy2209** [snesrev/zelda3#54]
It would be great if we could compile with MSYS2 instead of Visual Studio on Windows

**Comment by snesrev** [comment]
I don't have MSYS2. What issues do you run into?

**Comment by Fancy2209** [comment]
> I don't have MSYS2. What issues do you run into?

I just would prefer having a Alternative to using Visual Studio 
I tried msbuild but it failed

**Comment by Fancy2209** [comment]
I tried msys 2 but pip couldn't install pillow

**Comment by keatongreve** [comment]
I ran through a brand new MSYS2 setup on my machine. I think it should work, the issues seemed to have been related to MSYS's environment, and not the project itself. I took notes along the way. Also I'm in the mingw64.exe shell. I don'tthink the commands below will install the packages necessary to run in a MINGW32 shell.

### Commands you should try running
`pacman -S mingw-w64-x86_64-python3-pillow`
`pacman -S mingw-w64-x86_64-python-yaml`

I guess these packages in particular have some issues with the default setup, so there are MSYS packages to resolve this.

for SDL: `pacman -S mingw-w64-x86_64-SDL2`
verify:
```
$ sdl2-config --cflags
-IC:/msys64/mingw64/include/SDL2 -Dmain=SDL_main

$ sdl2-config --libs
-LC:/msys64/mingw64/lib -lmingw32 -mwindows -lSDL2main -lSDL2
```

for make: `pacman -S make` which installs /usr/bin/make
you can also try `pacman -S mingw-w64-x86_64-make`, but keep in mind this generates `/mingw64/bin/mingw32-make`
https://stackoverflow.com/questions/18020816/what-are-the-differences-between-mingws-make-and-msyss-make

for gcc: `pacman -S mingw-w64-x86_64-gcc`
there's also a plain `gcc` package, but i'd opt not to install it, i don't think it worked for me.

once that's all done, `make` worked and generated an `.exe`.

**Comment by Fancy2209** [comment]
> 

Thanks a lot!
I'll try this when I can, maybe this could be added to the build instructions?

**Comment by Fancy2209** [comment]
It worked! Thanks

**Comment by programmbauer** [comment]
I can confirm that the provided Makefile works nicely when using MSYS2's MINGW [environment](https://www.msys2.org/docs/environments/) (though I used the MINGW64 environment instead of MINGW32). I can also confirm that the MSYS environment is a bit more finicky. The packages listed by [keatongreve](https://github.com/keatongreve) look reasonable to me.

**Comment by snesrev** [comment]
I added this to the Wiki. However, I don't know how to edit wikis.
https://github.com/snesrev/zelda3/wiki
