### ISSUE TITLE
Volume control support

### ISSUE THREAD

**Issue by keatongreve** [snesrev/zelda3#55]
This is a tracking issue for all commits/PRs related to volume control support (cross-platform and non-cross-platform).

**Comment by FitzRoyX** [comment]
Are you just trying to avoid leaving fullscreen to access the system tray? What seems to be the problem?

**Comment by snesrev** [comment]
Any progress?

**Comment by keatongreve** [comment]
Just sent out https://github.com/snesrev/zelda3/pull/131 for review.

I got sidetracked for a while trying to implement the Mac equivalent of the Win32 API (unfortunately, I dont think this exists). I ended up essentially making audio output through an AVAudioEngine which can have its volume adjusted (see https://github.com/snesrev/zelda3/compare/master...keatongreve:zelda3:macos). This was when I figured out there were some issues with mono audio, so I got distracted on that.

I think after the Win32 PR is merged, we could probably consider this fixed. Introducing mac support would result in the application behaving way differently than Windows:
```
if Windows:
  audio output handled by SDL
  volume is controlled via OS volume mixer (ISimpleAudioVolume Win32 API), SDL output is always 100% volume.
if Mac:
  audio is output through AVFAudio
  volume is controlled via AVFAudio
  SDL audio is ignored
if Linux:
  audio output and volume handled by SDL
```

Setting it up like this is certainly possible, just might be complicated and unnecessary.

**Comment by FitzRoyX** [comment]
> My primary motivation was that my main platform (Mac) doesn't have a sound mixer

Oh so basically the volume control keys on a mac keyboard aren't working for this app?

**Comment by keatongreve** [comment]
No, you can adjust the global volume of your sound output device, just not individual applications like Windows' Sound mixer panel.

An end-user solution for the latter exists with third party software like eqMac2 or https://github.com/kyleneideck/BackgroundMusic.

**Comment by keatongreve** [comment]
However if you've used something like OpenEmu you might have noticed that it has its own volume control slider, which means it is possible to have an application control its own volume.
