### ISSUE TITLE
Option to ignore aspect ratio

### ISSUE THREAD

**Issue by mrdeathjr28** [snesrev/zelda3#56]
Hi maybe interesting add a option to ignore aspect ratio to prevent black areas like this

![zeldntv](https://user-images.githubusercontent.com/6601480/188337271-dbad199d-25cb-44c0-87b2-34b11bb6e04b.png)

thanks

**Comment by FitzRoyX** [comment]
Wouldn't that seriously distort the graphics?

**Comment by mrdeathjr28** [comment]
> Wouldn't that seriously distort the graphics?

yeah because i dont like black bars
