### ISSUE TITLE
Add requirements.txt

### ISSUE THREAD

**Issue by xackery** [snesrev/zelda3#60]
Just add a requirements.txt file with dependencies, e.g.

pip3 install Pillow
pip3 install pyyaml

fixed my 
ModuleNotFoundError: No module named 'PIL'
ModuleNotFoundError: No module named 'yaml'

**Comment by snesrev** [comment]
How does this help? It's already in README.md

**Comment by programmbauer** [comment]
Basically that file would enable the user to install all dependencies via `pip install -r requirements.txt` . You could even add this line to the makefile to automate that step completely.

**Comment by xackery** [comment]
You can use [pip freeze](https://pip.pypa.io/en/stable/cli/pip_freeze/) to output specific versions in requirements format, too, to ensure users are in sync with the version the developer intended, in cases a 3rd party package deviates heavily
