### ISSUE TITLE
FR: Fill rubies, bombs, and arrows

### ISSUE THREAD

**Issue by almostalive** [snesrev/zelda3#64]
As the title says. I figured this is a decent feature request since you have fill magic and life. Unless those are more difficult to implement.

P.S.  This is awesome!

**Comment by Goodlyay** [comment]
> Thanks! Now after 30 years I finally know what was on the other side of those cracked walls in that dungeon behind the throne. :D

There is a tombstone in the cemetery you're supposed to fall into which brings you back there later in the game, when you have bombs.
