### ISSUE TITLE
FR: An option in the config for the window zoom setting

### ISSUE THREAD

**Issue by JasonShearer** [snesrev/zelda3#66]
It currently doesn't save between sessions.

**Comment by Nutzzz** [comment]
I added a config section to the .ini in PR #39 (including a window zoom setting).  It doesn't currently save changes to use whatever the last setting was, but that was on my TODO.

**Comment by snesrev** [comment]
Fixed in 9c27ead94bfb768319d667d90a0e4ee41ecb4cb5

**Comment by Nutzzz** [comment]
Perhaps this should remain open to contain the suggestion to (optionally?) save the last used zoom/fullscreen setting.
