### ISSUE TITLE
FR: Pixel shader support

### ISSUE THREAD

**Issue by JasonShearer** [snesrev/zelda3#67]
Any chance of adding pixel shader support, such as the ones [found here](https://github.com/libretro/common-shaders)? Playing this with a nice scanline/CRT shader would be phenomenal.

**Comment by snesrev** [comment]
They seem to be of different license types. Anyone knows if I can add them to this repo?

**Comment by JasonShearer** [comment]
> They seem to be of different license types. Anyone knows if I can add them to this repo?

No idea. If this is problematic, a possible workaround (unless someone has a better idea) could be to make it so that the user can optionally add these external shader files to a subfolder, and perhaps you could include a couple of options in the config--one to enable/disable the shader (which could also include a hotkey), and the other to define whichever shader is being used based on its filename. Not exactly user friendly, but I presume most of the people here are building this from source anyway, so it shouldn't be an issue. For everyone else, it could be explained in the README.

**Comment by remutro** [comment]
Would love a scanline filter at a minimum

**Comment by snesrev** [comment]
This is added in 3be6ece9f9af832950699fb1c448d6eec8ebc47a
