### ISSUE TITLE
Crackling sound

### ISSUE THREAD

**Issue by malvarenga123** [snesrev/zelda3#69]
I'm getting crackling sound with a x64 build of the latest commit [3870ca7](https://github.com/snesrev/zelda3/commit/3870ca7517f18856e5e3eba9d067fb07fd97b7d2) in Windows.
It sounds a lot like when an emulator is trying to sync audio to video, usually they have an option to sync video to audio.
It doesn't matter if I use the old or the new renderer.

Is it possible to also see the actual framerate instead of the theoretical one?

**Comment by pikappa19** [comment]
I have the same problem

**Comment by FitzRoyX** [comment]
I had this problem as well. I think the issue is that there may not be a one-size-fits-all buffer size for people's audio cards. I have an onboard Realtek fwiw. Changing line 165 in main.c from 2048 to 1024 fixed the issue for me, so give it a shot.

**Comment by malvarenga123** [comment]
@FitzRoyX I also have an onboard Realtek. I tested changing both lines 124 and 188. The combination that almost (there are a few rare clicks or pops) solved the issue for me was having the frequency at 48000 and the buffer at 4096.

**Comment by FitzRoyX** [comment]
The stuff on line 124 is fairly new. I'm not smart enough to know what it's doing, but it seems to have helped reduce crackle. Also, I don't think it's my imagination, but building with 32000 sounds better than anything higher. Maybe it avoids resampling?

**Comment by Nutzzz** [comment]
Added sound options to .ini in PR #39

**Comment by snesrev** [comment]
Try playing around with the new sound options in the .ini

**Comment by FitzRoyX** [comment]
The ability to use 32000 seems to have been removed? 😕

**Comment by Nutzzz** [comment]
It should take any power of 2 greater than 0 or less than or equal to 48000. Note that "e.g." means "for example;" the listed values are not exclusive.

**Comment by FitzRoyX** [comment]
https://user-images.githubusercontent.com/57089001/189492586-33a9f7a7-95bd-4e0e-bf8d-95b54b5a88d8.mp4

Rupee sound effect comparison. 32000 before and after your changes. Also, setting to 11025 doesn't make it sound any different from 44100, so it's like the setting is having no effect and is hardcoded atm.

**Comment by Nutzzz** [comment]
You're quite right!  Those aren't powers of two; that guard is incorrect.  It looks like #79 fixes my oops.

**Comment by snesrev** [comment]
Try with the latest master. Texture rendering was really slow on some computers. Reopen this bug if it still doesn't work.
