### ISSUE TITLE
Feature Request: Integer scaling in fullscreen mode

### ISSUE THREAD

**Issue by UltraHDR** [snesrev/zelda3#72]
Black bars are fine to avoid blur

**Comment by UltraHDR** [comment]
It already is

**Comment by UltraHDR** [comment]
You can CTRL + scroll up/down on the mouse wheel in full screen mode to change it to Integer scaling

**Comment by FitzRoyX** [comment]
Uhh, no you can't. At least not on windows. Why did you close this?
