### ISSUE TITLE
Generate ini if missing

### ISSUE THREAD

**Issue by f0n1x** [snesrev/zelda3#78]
Request to generate an ini if not present, preferably following the XDG spec:
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by snesrev** [comment]
Why not just use the bundled ini

**Comment by f0n1x** [comment]
That is fine, but I suppose the real question I have is... In which location is the executable expecting to find the ini file? I assume that would be the same location as the binary. However, on Linux, the correct location to place binaries is /usr/bin and an ini file would not go in here, as it wouldn't be user editable. It would need to be placed in user's home folder likely under either .config or .local. The path would be something like /home/<username>/.local/zelda3 (where <username> is defined in $HOME).

**Comment by snesrev** [comment]
Fxed so it chdirs to zelda3.ini in 6bd8b1185e7a9a1d80b4d9a10fbf6e04b767de4c
Why not store zelda3 executables in /.local/zelda3 too?

**Comment by f0n1x** [comment]
Technically, you could store it anywhere, it's just best practice to place binaries in /usr/bin and user editable files in /home/\<user\>/.local/\<program\>/ or /home/\<user\>/.config/\<program\>/
