### ISSUE TITLE
Copy .ini, .dat, and /saves/ref to bin (OutDir)

### ISSUE THREAD

**Issue by Nutzzz** [snesrev/zelda3#84]
Though the initial complaint in #74 was resolved by hunting for zelda.ini in a couple of steps of parent directories in 6bd8b11, that commit doesn't resolve the similar problem with /save/refs.  Nor is it obvious which files are necessary if you want to only capture the necessary files of a binary release.  #76 is an attempt at a general solution for Visual Studio, but the general idea should apply to the makefile as well (though perhaps it could be contained in an install macro).

> Hm... this only deals with the situation where you're debugging the game from within VS or running it from the location it built in as a subdirectory of the source tree.  No matter how it's built, It's nice to be able to have everything you need to play the game in its own folder so that the files can then easily be moved elsewhere, i.e., decouple src and bin.
>
> And it doesn't help with the /saves/ref folder.
>
> Note I moved this pull to a separate branch [http://github.com/Nutzzz/zelda3/tree/output_folder](https://github.com/Nutzzz/zelda3/tree/output_folder)

_Originally posted by @Nutzzz in https://github.com/snesrev/zelda3/issues/76#issuecomment-1243105710_

**Comment by snesrev** [comment]
I can't have the saves in the build folder, because when I switch between Release and Debug mode i wouldn't be able to load my other saves.

**Comment by snesrev** [comment]
Why <LinkIncremental>false</LinkIncremental>

**Comment by snesrev** [comment]
How about a package.py script that zips all the files you need into a zip-file?

**Comment by Nutzzz** [comment]
Re: saves in the build folder, CopyToOutputDirectory moves them to wherever OutDir is.  If you don't like having an extra copy in both Debug and Release, I suppose you could do as you suggested in #74 and use a consistent OutDir but with differing names for the .exe files.

Re: LinkIncremental, I set it off for release (but not debug) because unlike the .pdb which I moved to the IntDir build directory, there's no way to change the location of the .ilk file from OutDir.  Perhaps another solution would be better (e.g., a post-build step; and of course you could use that instead of CopyToOutputDirectory).

Re: a python solution, I suppose it sort of meets my suggestion in a cross-platform way, though I obviously prefer having a clean bin directory with which I can do whatever I want (e.g., a simple copy to another install location), and I personally prefer using a makefile with install/package macros for non-VS builds.

**Comment by snesrev** [comment]
The makefile could invoke the python script to install things

**Comment by snesrev** [comment]
I don't know how to move forward with this.

**Comment by Nutzzz** [comment]
> I don't know how to move forward with this.

Well, if you're OK with not using a common python script, I've got an updated MSVS version in a branch in my fork: https://github.com/Nutzzz/zelda3/tree/output_folder

This follows your suggestion to have just one /bin OutDir with differing OutputFile names (e.g., zelda3-x86-debug.exe) so your /saves persist in a single location.

**Comment by snesrev** [comment]
I don't really this.... Perhaps we could add a third build option called BundleRelease or something that does this?

**Comment by Nutzzz** [comment]
I remain slightly confused about what you like and don't like about this idea (beyond the couple of things that have already been implemented, thanks), but I went back to separate OutDirs and added a ReleaseDeploy configuration in my [fork](/Nutzzz/zelda3/tree/output_folder).

Note that Build won't replace an existing .ini but Rebuild does.

**Comment by Nutzzz** [comment]
...and now it looks like the .dat needs to be copied as well.

**Comment by snesrev** [comment]
Fixed in 8ee08ac4c212496e807b86f63a3e34cc7a590aee
