### ISSUE TITLE
Extended aspect ratio not working

### ISSUE THREAD

**Issue by Sirethief2525** [snesrev/zelda3#89]
So I updated to the latest code this morning to try out the 16:9 aspect ratio and no matter how I configure the ini file and regardless of if I'm running it fullscreen or windowed I can't seem to get it to work. Maybe I'm misunderstanding what the enhancement does or maybe there is some other else I'm doing wrong, any help on the matter would be much appreciated. Thank-you for all of the hard work you've put into making this port a reality.

**Comment by patrickmollohan** [comment]
It seemingly works for me on Linux (haven't tested on Windows). To verify, your config file contains
```ExtendedAspectRatio = 16:9```?
Also worth noting, it won't stretch the image or display more than what exists. So for instance, there isn't more to the first room in the game, so it still looks like this:
![image](https://user-images.githubusercontent.com/14967142/190427255-201c0bb6-3ea9-459d-ba78-9e6b6719258c.png)
but if you go outside where there is more than one screen loaded, it will look like this:
![image](https://user-images.githubusercontent.com/14967142/190427572-a2a95841-a85a-4071-b8fa-e01c8cdee661.png)

**Comment by Sirethief2525** [comment]
[
![image](https://user-images.githubusercontent.com/4690899/190441949-21dc7f74-73cf-4342-9828-ea59f426988f.png)
](url)
![image](https://user-images.githubusercontent.com/4690899/190442248-ccda9523-bef0-4d64-bc6c-f66619d12165.png)

**Comment by FitzRoyX** [comment]
The line to enable it is deactivated by turning it into a comment. In programming terms this is called being "commented out." In this case comments are defined with a # in front. So the line "# ExtendedAspectRatio = 16:10" needs to have its # sign removed.

**Comment by Sirethief2525** [comment]
Thank-you, that seems to have fixed it.

**Comment by Sirethief2525** [comment]
Sorry for the late replies, I work overnights at the moment.

**Comment by snesrev** [comment]
Made this slightly clearer in 312be71259a0ac8ee7eeb70f8b9b87589b7cdee5. Closing.
