### ISSUE TITLE
Idea: Extended view to allow ultimate widescreen with integer scale

### ISSUE THREAD

**Issue by UltraHDR** [snesrev/zelda3#91]
Thanks for your hard work on the widescreen patch!

Is it possible to use integer scaling and then fill out the rest of the graphics around it (North East South West)? Thanks

Something similar to https://prilik.com/ANESE/wideNES.html
![image](https://user-images.githubusercontent.com/108294295/190523781-86bfb009-99cb-418b-a2d4-ccc13c1916f1.png)

**Comment by snesrev** [comment]
I don't understand

**Comment by UltraHDR** [comment]
![int scaling](https://user-images.githubusercontent.com/108294295/190530541-801e8a89-c929-4f74-bf2a-734998dd11a3.png)

With integer scaling there are black borders on the top, bottom and right. Is it possible to fill the black borders with extra sprites? Thanks

**Comment by FitzRoyX** [comment]
Not possible with integer scaling. The closest you could get to being black bar free is a resolution of 480x240 which at 4x would be 1920x960. You'd have to expand the vres to the snes max of 240 to achieve that, otherwise it's 1920x896.

**Comment by snesrev** [comment]
I've added support for 240 pixels height. Not much more can be done.

**Comment by UltraHDR** [comment]
Thanks @snesrev for your hard work. The existing enchancements are awesome. I am just being greedy!
