### ISSUE TITLE
Old renderer broken, new renderer has too bright map screen

### ISSUE THREAD

**Issue by patrickmollohan** [snesrev/zelda3#92]
While testing my PR for 18:9 support for any anomalies, I found the old renderer is broken, including on a fresh build without my modifications. Certain elements get shifted to the right when switching between the old and new renderers. Additionally, the map screen gets dimmer on the old renderer, which is correct, whereas the new renderer is brighter than it should be.
Old renderer (incorrect):
![image](https://user-images.githubusercontent.com/14967142/190667817-32e2ef43-df52-4c2c-bf85-9c447f60efd6.png)
New renderer (correct):
![image](https://user-images.githubusercontent.com/14967142/190667980-176e046d-708e-4fe6-bc10-a8ee3296aa3e.png)
Old renderer:
![image](https://user-images.githubusercontent.com/14967142/190668210-8e6c66e5-704b-4186-a7ac-c5da8a064d56.png)
New renderer:
![image](https://user-images.githubusercontent.com/14967142/190668448-c0ff7fef-b91a-4a6b-936b-779e1e115859.png)
Old renderer:
![image](https://user-images.githubusercontent.com/14967142/190668701-d8933a9e-a859-4a12-8732-135724195dad.png)
New renderer:
![image](https://user-images.githubusercontent.com/14967142/190668768-56fe2a84-2e7c-4090-b065-deb23a191577.png)

For comparison, here is the map in Snes9x:
![image](https://user-images.githubusercontent.com/14967142/190672543-02ddae56-387a-4dc1-95b8-cd7fa36b9e0c.png)
(I'm in a different spot in Snes9x; just wanted to take a screenshot in roughly the same area)

**Comment by snesrev** [comment]
I didn't add 16:9 support to the old renderer. Is that why?

**Comment by snesrev** [comment]
I'm not able to reproduce the issue of the map screen having too bright colors.... For me the old and new renderer look similar.

**Comment by snesrev** [comment]
I had forgot to commit a fix to the old renderer. Please try again now.

**Comment by patrickmollohan** [comment]
The sprite issue is now fixed! The brightness is still the same though. Perhaps a Windows vs Linux thing?

**Comment by patrickmollohan** [comment]
It appears to be related to EnhancedMode7. Disabling it fixes the brightness issue.

**Comment by snesrev** [comment]
I still can't reproduce it. Not sure what I'm doing wrong...

**Comment by patrickmollohan** [comment]
That is really bizarre. I'll compile on my Windows machine tonight and see if that could be the difference.

**Comment by patrickmollohan** [comment]
Same thing on Windows 10:
![Zelda3](https://user-images.githubusercontent.com/14967142/190721980-dd22657d-c774-4957-ace7-93ad0c9c31c5.PNG)
Just installed VS/Python + dependencies, pretty much a clean install of Windows 10 since I barely use it on this machine. Pulled the GitHub repo using VS, tho in Linux I just used git clone via terminal. No changes to the config file or code. Using the ROM listed in the readme (SHA256: 66871d66be19ad2c34c927d6b14cd8eb6fc3181965b6e517cb361f7316009cfb).

**Comment by snesrev** [comment]
I AM getting the bright screen. But I'm getting that both with old and new renderer. Not getting the darker screen like you do. Is this the same behavior as your windows install?

**Comment by FitzRoyX** [comment]
> I AM getting the bright screen. But I'm getting that both with old and new renderer. Not getting the darker screen like you do. Is this the same behavior as your windows install?

The darker world map is only in the beginning when it's raining outside.

**Comment by snesrev** [comment]
> The darker world map is only in the beginning when it's raining outside.
Ok now I can reproduce it. Thanks. It's because I don't implement the ppu color math (in this case I guess halving) for the 4x4 upsampled mode.
