### ISSUE TITLE
on macOS with Integer scale in fullscreen mode the image is not rendered in the center and rendered in the center of the mouse

### ISSUE THREAD

**Issue by UltraHDR** [snesrev/zelda3#97]
Currently it's not in the center

<img width="1728" alt="Screenshot 2022-09-18 at 8 19 54 pm" src="https://user-images.githubusercontent.com/108294295/190924713-8144d99d-c2d9-46ed-b17b-67d044e6b6dd.png">

Steps to reproduce
1. Launch ./zelda3
2. Click the green full screen button
3. CTRL + roll scroll wheel and the render will be at the center of the mouse cursor

Steps that doesn't have this bug but also disables CTRL + scroll wheel
1. Launch ./zelda3
2. Press ALT + ENTER
3. CTRL + roll scroll wheel  does nothing

**Comment by FitzRoyX** [comment]
The area on the right is the map boundary. The map literally ends there, there's nothing to display.

**Comment by UltraHDR** [comment]
@FitzRoyX OK the screenshot wasn't the best example but i've edited my top post with another one.

**Comment by FitzRoyX** [comment]
I don't even understand how you're doing integer scaling in fullscreen. There is no setting for it and ctrl+arrow doesn't do anything in that mode.

**Comment by UltraHDR** [comment]
@FitzRoyX  CTRL + Scroll the Mouse Wheel

**Comment by snesrev** [comment]
i'm not able to reproduce this. For me it's always centered. Windows vs linux issue?

**Comment by UltraHDR** [comment]
This is macOS

**Comment by UltraHDR** [comment]
It's intentional and is due to "Center the window on top of the mouse"

https://github.com/snesrev/zelda3/blob/master/main.c#L112
