### ISSUE TITLE
The old renderer isn't playing nice with widescreen

### ISSUE THREAD

**Issue by JasonShearer** [snesrev/zelda3#98]
Using the old renderer with a widescreen aspect ratio causes this to happen.

![zelda3_2022-09-18_21-25-44](https://user-images.githubusercontent.com/14334181/190950271-0481712a-6246-4d82-af58-308d87ceffc9.png)

**Comment by patrickmollohan** [comment]
Can confirm on Windows and Linux.

**Comment by FitzRoyX** [comment]
What's the advantage of the old renderer? Do we need it anymore?

**Comment by patrickmollohan** [comment]
It's good for spotting anomalies at the very least.
